# Default values for kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

apiserver:
  replicaCount: 1

  service:
    type: ClusterIP
    port: 443
    loadBalancerIP: 172.18.201.151
    clusterIP: 10.254.0.99

controllerManager:
  replicaCount: 1

scheduler:
  replicaCount: 1

image:
  repository: gcr.io/google_containers/hyperkube
  tag: v1.9.2
  pullPolicy: IfNotPresent

etcdServer:
  host: etcd-client
  port: 2379

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true
  apiVersion: v1
