apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ template "kubernetes.fullname" . }}-etcd
  labels:
    app: {{ template "kubernetes.name" . }}-etcd
    chart: {{ template "kubernetes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.etcdCluster.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  size: {{ .Values.etcdCluster.replicaCount }}
  version: {{ .Values.etcdCluster.version }}
