apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ template "kubernetes.fullname" . }}-etcd
  # Adding this annotation make this cluster managed by clusterwide operators
  # namespaced operators ignore it
  labels:
    app: {{ template "kubernetes.name" . }}-etcd
    chart: {{ template "kubernetes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: {{ .Values.etcdCluster.replicaCount }}
  version: {{ .Values.etcdCluster.version }}
